create table custorder(cid int,supplyname nvarchar(20),cs int,shippingname nchar(20),proprice nvarchar(20),pstockstatus nvarchar(20),pordered int,cmpyname nvarchar(20));
insert into custorder values(1,'Exotic',5000,'rjy',1000,'instock',10,'aaa');
insert into custorder values(2,'Exc',6000,'ry',5000,'onstock',10,'baa');
insert into custorder values(3,'tic',1000,'jy',600,'outofstock',10,'aya');
select * from custorder;
select proprice,shippingname from custorder where cs>50 and supplyname='Exotic';
create table employee(eid int primary key ,ename text,empcity varchar(10));
insert into employee values(1,'sreya','amp');
insert into employee values(2,'sreja','rjy');
insert into employee values(3,'seeta','hyd','2022-03-01');
insert into employee values(4,'sema','vjy','2005-03-01');

select * from employee;
alter table employee add doj date;
update employee set doj='2002-02-01' where eid=1;
update employee set doj='2010-02-01' where eid=2;
create table c(cid int primary key,cname text);
insert into c values(1,'paul');
insert into c values(2,'sri');
select * from c;
select cid from c where cname like 'ra%';
select * from c;
select * from employee where doj>'2002-02-01' ;
select * from employee where doj<'2002-02-01';
select * from custorder;
select proprice from custorder where proprice>100 order by proprice; 
select supplyname from custorder where pstockstatus='outofstock';
select * from custorder; 
select pordered,cid from custorder where pordered>=10;
select cmpyname from custorder where cmpyname like 'a%';